
const Message = require('./api/message');
const fs = require('fs');
const Functions = require('./api/functions');
const config = require('./config.json');

const mysqlObject = require('mysql');

let mysql = mysqlObject.createPool({
    "host": config.mysql.host,
    "user": config.mysql.user,
    "password": config.mysql.password
});


const queries = [
    `CREATE DATABASE IF NOT EXISTS ${config.mysql.database} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_assault_match_objectives (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        map int(11) NOT NULL,
        timestamp float NOT NULL,
        obj_id int(11) NOT NULL,
        player int(11) NOT NULL,
        bfinal int(11) NOT NULL,
        PRIMARY KEY (id))
        ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_assault_objects (
        id int(11) NOT NULL AUTO_INCREMENT,
        map int(11) NOT NULL,
        obj_order int(11) NOT NULL,
        name varchar(100) NOT NULL,
        obj_id int(11) NOT NULL,
        matches int(11) NOT NULL,
        taken int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_countries (
        id int(11) NOT NULL AUTO_INCREMENT,
        code varchar(2) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        total int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE IF NOT EXISTS nstats_ctf_caps (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        cap_team int NOT NULL,
        flag_team int NOT NULL,
        grab_time float NOT NULL,
        grab_player int NOT NULL,
        cap_time float NOT NULL,
        cap_player int NOT NULL,
        travel_time float NOT NULL,
        carry_time float NOT NULL,
        carry_time_percent float NOT NULL,
        drop_time float NOT NULL,
        drop_time_percent float NOT NULL,
        total_drops int NOT NULL,
        total_pickups int NOT NULL,
        total_covers int NOT NULL,
        total_seals int NOT NULL,
        total_assists int NOT NULL,
        total_self_covers int NOT NULL,
        total_deaths int NOT NULL,
        total_suicides int NOT NULL,
        team_0_kills int NOT NULL,
        team_1_kills int NOT NULL,
        team_2_kills int NOT NULL,
        team_3_kills int NOT NULL,
        team_0_suicides int NOT NULL,
        team_1_suicides int NOT NULL,
        team_2_suicides int NOT NULL,
        team_3_suicides int NOT NULL,
        PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_ctf_assists (
      id int NOT NULL AUTO_INCREMENT,
      match_id int NOT NULL,
      match_date int NOT NULL,
      map_id int NOT NULL,
      cap_id int NOT NULL,
      player_id int NOT NULL,
      pickup_time float NOT NULL,
      dropped_time float NOT NULL,
      carry_time float NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE IF NOT EXISTS nstats_ctf_covers (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        cap_id int NOT NULL,
        timestamp float NOT NULL,
        killer_id int NOT NULL,
        killer_team int NOT NULL,
        victim_id int NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE IF NOT EXISTS nstats_ctf_self_covers (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        cap_id int NOT NULL,
        timestamp float NOT NULL,
        killer_id int NOT NULL,
        killer_team int NOT NULL,
        victim_id int NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE IF NOT EXISTS nstats_ctf_seals (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        cap_id int NOT NULL,
        timestamp float NOT NULL,
        killer_id int NOT NULL,
        victim_id int NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE IF NOT EXISTS nstats_ctf_carry_times (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        cap_id int NOT NULL,
        flag_team int NOT NULL,
        player_id int NOT NULL,
        player_team int NOT NULL,
        start_time float NOT NULL,
        end_time float NOT NULL,
        carry_time float NOT NULL,
        carry_percent float NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE IF NOT EXISTS nstats_ctf_returns (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        flag_team int NOT NULL,
        grab_time float NOT NULL,
        grab_player int NOT NULL,
        return_time float NOT NULL,
        return_player int NOT NULL,
        return_string VARCHAR(60) NOT NULL,
        distance_to_cap float NOT NULL,
        pos_x float NOT NULL,
        pos_y float NOT NULL,
        pos_z float NOT NULL,
        travel_time float NOT NULL,
        carry_time float NOT NULL,
        carry_time_percent float NOT NULL,
        drop_time float NOT NULL,
        drop_time_percent float NOT NULL,
        total_drops int NOT NULL,
        total_pickups int NOT NULL,
        total_covers int NOT NULL,
        total_seals int NOT NULL,
        total_self_covers int NOT NULL,
        total_deaths int NOT NULL,
        total_suicides int NOT NULL,
        team_0_kills int NOT NULL,
        team_1_kills int NOT NULL,
        team_2_kills int NOT NULL,
        team_3_kills int NOT NULL,
        team_0_suicides int NOT NULL,
        team_1_suicides int NOT NULL,
        team_2_suicides int NOT NULL,
        team_3_suicides int NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE IF NOT EXISTS nstats_ctf_flag_deaths (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        timestamp float NOT NULL,
        cap_id int NOT NULL,
        killer_id int NOT NULL,
        killer_team int NOT NULL,
        victim_id int NOT NULL,
        victim_team int NOT NULL,
        kill_distance float NOT NULL,
        distance_to_cap float NOT NULL,
        distance_to_enemy_base float NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE nstats_ctf_flag_drops (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        timestamp float NOT NULL,
        cap_id int NOT NULL,
        flag_team int NOT NULL,
        player_id int NOT NULL,
        player_team int NOT NULL,
        distance_to_cap float NOT NULL,
        position_x float NOT NULL,
        position_y float NOT NULL,
        position_z float NOT NULL,
        time_dropped float NOT NULL,
        PRIMARY KEY(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
      `CREATE TABLE nstats_ctf_flag_pickups (
        id int NOT NULL AUTO_INCREMENT,
        match_id int NOT NULL,
        match_date int NOT NULL,
        map_id int NOT NULL,
        cap_id int NOT NULL,
        timestamp float NOT NULL,
        player_id int NOT NULL,
        player_team int NOT NULL,
        flag_team int NOT NULL,
        PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
        `CREATE TABLE nstats_ctf_cr_kills (
          id int NOT NULL AUTO_INCREMENT,
          match_id int NOT NULL,
          match_date int NOT NULL,
          map_id int NOT NULL,
          cap_id int NOT NULL,
          event_type int NOT NULL,
          timestamp float NOT NULL,
          player_id int NOT NULL,
          player_team int NOT NULL,
          total_events int NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_ctf_events (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp float NOT NULL,
        player int(11) NOT NULL,
        event varchar(30) NOT NULL,
        team int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_dom_control_points (
        id int(11) NOT NULL AUTO_INCREMENT,
        map int(11) NOT NULL,
        name varchar(100) NOT NULL,
        captured int(11) NOT NULL,
        matches int(11) NOT NULL,
        x float NOT NULL,
        y float NOT NULL,
        z float NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_dom_match_caps (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        time float NOT NULL,
        player int(11) NOT NULL,
        point int(11) NOT NULL,
        team int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_dom_match_control_points (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        map int(11) NOT NULL,
        name varchar(100) NOT NULL,
        captured int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_dom_match_player_score (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp float NOT NULL,
        player int(11) NOT NULL,
        score int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_faces (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        uses int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_ftp (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        host varchar(250) NOT NULL,
        port int(11) NOT NULL,
        user varchar(50) NOT NULL,
        password varchar(50) NOT NULL,
        target_folder varchar(250) NOT NULL,
        delete_after_import tinyint(1) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        total_imports int(11) NOT NULL,
        delete_tmp_files int(1) NOT NULL,
        total_logs_imported int(11) NOT NULL,
        ignore_bots int(1) NOT NULL,
        ignore_duplicates int(1) NOT NULL,
        min_players int(2) NOT NULL,
        min_playtime int(11) NOT NULL,
        sftp int(1) NOT NULL,
        import_ace INT(1) NOT NULL,
        delete_ace_logs int(1) NOT NULL,
        delete_ace_screenshots int(1) NOT NULL,
        total_ace_kick_logs INT(1) NOT NULL,
        total_ace_join_logs INT(1) NOT NULL,
        total_ace_screenshots INT(1) NOT NULL,
        enabled INT(1) NOT NULL,
        use_ace_player_hwid INT(1) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

      `CREATE TABLE IF NOT EXISTS nstats_logs_folder (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        total_imports int(11) NOT NULL,
        total_logs_imported int(11) NOT NULL,
        ignore_bots int(1) NOT NULL,
        ignore_duplicates int(1) NOT NULL,
        min_players int(2) NOT NULL,
        min_playtime int(11) NOT NULL,
        import_ace INT(1) NOT NULL,
        total_ace_kick_logs INT(1) NOT NULL,
        total_ace_join_logs INT(1) NOT NULL,
        total_ace_screenshots INT(1) NOT NULL,
        use_ace_player_hwid INT(1) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

    `CREATE TABLE IF NOT EXISTS nstats_gametypes (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        matches int(11) NOT NULL,
        playtime double NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_headshots (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp float NOT NULL,
        killer int(11) NOT NULL,
        victim int(11) NOT NULL,
        distance float NOT NULL,
        killer_team int(11) NOT NULL,
        victim_team int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_items (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        display_name varchar(100) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        uses int(11) NOT NULL,
        matches int(11) NOT NULL,
        type int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_items_match (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        player_id int(11) NOT NULL,
        item int(11) NOT NULL,
        uses int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
      `,
    `CREATE TABLE IF NOT EXISTS nstats_items_player (
        id int(11) NOT NULL AUTO_INCREMENT,
        player int(11) NOT NULL,
        item int(11) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        uses int(11) NOT NULL,
        matches int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_kills (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp float NOT NULL,
        killer int(11) NOT NULL,
        killer_team int(11) NOT NULL,
        victim int(11) NOT NULL,
        victim_team int(11) NOT NULL,
        killer_weapon int(11) NOT NULL,
        victim_weapon int(11) NOT NULL,
        distance float NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_logs (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        imported int(11) NOT NULL,
        match_id int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_maps (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        title varchar(100) NOT NULL,
        author varchar(100) NOT NULL,
        ideal_player_count varchar(100) NOT NULL,
        level_enter_text varchar(100) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        matches int(11) NOT NULL,
        playtime double NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_maps_flags (
        id int(11) NOT NULL AUTO_INCREMENT,
        map int(11) NOT NULL,
        team int(11) NOT NULL,
        x float NOT NULL,
        y float NOT NULL,
        z float NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_map_spawns (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(50) NOT NULL,
        map int(11) NOT NULL,
        x double NOT NULL,
        y double NOT NULL,
        z double NOT NULL,
        spawns int(11) NOT NULL,
        team int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_matches (
        id int(11) NOT NULL AUTO_INCREMENT,
        date int(11) NOT NULL,
        server int(11) NOT NULL,
        gametype int(11) NOT NULL,
        map int(11) NOT NULL,
        version int(11) NOT NULL,
        min_version int(11) NOT NULL,
        admin varchar(50) NOT NULL,
        email varchar(100) NOT NULL,
        region int(11) NOT NULL,
        motd text NOT NULL,
        mutators text NOT NULL,
        playtime float NOT NULL,
        end_type varchar(50) NOT NULL,
        start float NOT NULL,
        end float NOT NULL,
        insta int(11) NOT NULL,
        team_game int(11) NOT NULL,
        game_speed int(11) NOT NULL,
        hardcore int(11) NOT NULL,
        tournament int(11) NOT NULL,
        air_control float NOT NULL,
        use_translocator int(11) NOT NULL,
        friendly_fire_scale float NOT NULL,
        net_mode varchar(100) NOT NULL,
        max_spectators int(11) NOT NULL,
        max_players int(11) NOT NULL,
        total_teams int(11) NOT NULL,
        players int(11) NOT NULL,
        time_limit int(11) NOT NULL,
        target_score int(11) NOT NULL,
        dm_winner int(11) NOT NULL,
        dm_score int(11) NOT NULL,
        team_score_0 float NOT NULL,
        team_score_1 float NOT NULL,
        team_score_2 float NOT NULL,
        team_score_3 float NOT NULL,
        attacking_team int(11) NOT NULL,
        assault_caps int(11) NOT NULL,
        dom_caps int(11) NOT NULL,
        mh_kills int(11) NOT NULL,
        mh int(11) NOT NULL,
        views int(11) NOT NULL,
        ping_min_average float NOT NULL,
        ping_average_average float NOT NULL,
        ping_max_average float NOT NULL,
        amp_kills int(11) NOT NULL,
        amp_kills_team_0 int(11) NOT NULL,
        amp_kills_team_1 int(11) NOT NULL,
        amp_kills_team_2 int(11) NOT NULL,
        amp_kills_team_3 int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_match_connections (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp float NOT NULL,
        player int(11) NOT NULL,
        event tinyint(4) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_match_pings (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp int(11) NOT NULL,
        player int(11) NOT NULL,
        ping int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_match_player_score (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp float NOT NULL,
        player int(11) NOT NULL,
        score int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
      `,
    `CREATE TABLE IF NOT EXISTS nstats_match_team_changes (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp float NOT NULL,
        player int(11) NOT NULL,
        team int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
      `,
    `CREATE TABLE IF NOT EXISTS nstats_monsters (
        id int(11) NOT NULL AUTO_INCREMENT,
        class_name varchar(150) COLLATE utf8_unicode_ci NOT NULL,
        display_name varchar(50) COLLATE utf8_unicode_ci NOT NULL,
        matches int(11) NOT NULL,
        deaths int(11) NOT NULL,
        kills int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_monsters_match (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        monster int(11) NOT NULL,
        deaths int(11) NOT NULL,
        kills int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_monsters_player_match (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        player int(11) NOT NULL,
        monster int(11) NOT NULL,
        kills int(11) NOT NULL,
        deaths int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_monsters_player_totals (
        id int(11) NOT NULL AUTO_INCREMENT,
        player int(11) NOT NULL,
        monster int(11) NOT NULL,
        matches int(11) NOT NULL,
        kills int(11) NOT NULL,
        deaths int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_monster_kills (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        timestamp float NOT NULL,
        monster int(11) NOT NULL,
        player int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_nexgen_stats_viewer (
        id int(11) NOT NULL AUTO_INCREMENT,
        title varchar(100) COLLATE utf8_unicode_ci NOT NULL,
        type int(11) NOT NULL,
        gametype int(11) NOT NULL,
        players int(11) NOT NULL,
        position int(11) NOT NULL,
        enabled tinyint(1) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_player_maps (
        id int(11) NOT NULL AUTO_INCREMENT,
        map int(11) NOT NULL,
        player int(11) NOT NULL,
        first int(11) NOT NULL,
        first_id int(11) NOT NULL,
        last int(11) NOT NULL,
        last_id int(11) NOT NULL,
        matches int(11) NOT NULL,
        playtime double NOT NULL,
        longest float NOT NULL,
        longest_id int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_player_matches (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        match_date int(11) NOT NULL,
        map_id int(11) NOT NULL,
        player_id int(11) NOT NULL,
        hwid varchar(32) NOT NULL,
        bot tinyint(1) NOT NULL,
        spectator tinyint(1) NOT NULL,
        played tinyint(1) NOT NULL,
        ip varchar(50) NOT NULL,
        country varchar(5) NOT NULL,
        face int(11) NOT NULL,
        voice int(11) NOT NULL,
        gametype int(11) NOT NULL,
        winner int(11) NOT NULL,
        draw int(11) NOT NULL,
        playtime float NOT NULL,
        team_0_playtime float NOT NULL,
        team_1_playtime float NOT NULL,
        team_2_playtime float NOT NULL,
        team_3_playtime float NOT NULL,
        spec_playtime float NOT NULL,
        team int(1) NOT NULL,
        first_blood int(1) NOT NULL,
        frags int(11) NOT NULL,
        score int(11) NOT NULL,
        kills int(11) NOT NULL,
        deaths int(11) NOT NULL,
        suicides int(11) NOT NULL,
        team_kills int(11) NOT NULL,
        spawn_kills int(11) NOT NULL,
        efficiency float NOT NULL,
        multi_1 int(11) NOT NULL,
        multi_2 int(11) NOT NULL,
        multi_3 int(11) NOT NULL,
        multi_4 int(11) NOT NULL,
        multi_5 int(11) NOT NULL,
        multi_6 int(11) NOT NULL,
        multi_7 int(11) NOT NULL,
        multi_best int(11) NOT NULL,
        spree_1 int(11) NOT NULL,
        spree_2 int(11) NOT NULL,
        spree_3 int(11) NOT NULL,
        spree_4 int(11) NOT NULL,
        spree_5 int(11) NOT NULL,
        spree_6 int(11) NOT NULL,
        spree_7 int(11) NOT NULL,
        spree_best int(11) NOT NULL,
        best_spawn_kill_spree int(11) NOT NULL,
        assault_objectives int(11) NOT NULL,
        dom_caps int(11) NOT NULL,
        dom_caps_best_life int(11) NOT NULL,
        ping_min int(11) NOT NULL,
        ping_average int(11) NOT NULL,
        ping_max int(11) NOT NULL,
        accuracy float NOT NULL,
        shortest_kill_distance float NOT NULL,
        average_kill_distance float NOT NULL,
        longest_kill_distance float NOT NULL,
        k_distance_normal int(11) NOT NULL,
        k_distance_long int(11) NOT NULL,
        k_distance_uber int(11) NOT NULL,
        headshots int(11) NOT NULL,
        shield_belt int(11) NOT NULL,
        amp int(11) NOT NULL,
        amp_time float NOT NULL,
        invisibility int(11) NOT NULL,
        invisibility_time float NOT NULL,
        pads int(11) NOT NULL,
        armor int(11) NOT NULL,
        boots int(11) NOT NULL,
        super_health int(11) NOT NULL,
        mh_kills int(11) NOT NULL,
        mh_kills_best_life int(11) NOT NULL,
        views int(11) NOT NULL,
        mh_deaths int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_player_totals (
        id int(11) NOT NULL AUTO_INCREMENT,
        hwid varchar(32) NOT NULL,
        name varchar(30) NOT NULL,
        player_id int(11) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        ip varchar(50) NOT NULL,
        country varchar(2) NOT NULL,
        face int(100) NOT NULL,
        voice int(11) NOT NULL,
        gametype int(11) NOT NULL,
        matches int(11) NOT NULL,
        wins int(11) NOT NULL,
        losses int(11) NOT NULL,
        draws int(11) NOT NULL,
        winrate float NOT NULL,
        playtime double NOT NULL,
        team_0_playtime float NOT NULL,
        team_1_playtime float NOT NULL,
        team_2_playtime float NOT NULL,
        team_3_playtime float NOT NULL,
        spec_playtime float NOT NULL,
        first_bloods int(11) NOT NULL,
        frags int(11) NOT NULL,
        score int(11) NOT NULL,
        kills int(11) NOT NULL,
        deaths int(11) NOT NULL,
        suicides int(11) NOT NULL,
        team_kills int(11) NOT NULL,
        spawn_kills int(11) NOT NULL,
        efficiency float NOT NULL,
        multi_1 int(11) NOT NULL,
        multi_2 int(11) NOT NULL,
        multi_3 int(11) NOT NULL,
        multi_4 int(11) NOT NULL,
        multi_5 int(11) NOT NULL,
        multi_6 int(11) NOT NULL,
        multi_7 int(11) NOT NULL,
        multi_best int(11) NOT NULL,
        spree_1 int(11) NOT NULL,
        spree_2 int(11) NOT NULL,
        spree_3 int(11) NOT NULL,
        spree_4 int(11) NOT NULL,
        spree_5 int(11) NOT NULL,
        spree_6 int(11) NOT NULL,
        spree_7 int(11) NOT NULL,
        spree_best int(11) NOT NULL,
        fastest_kill float NOT NULL,
        slowest_kill float NOT NULL,
        best_spawn_kill_spree int(11) NOT NULL,
        assault_objectives int(11) NOT NULL,
        dom_caps int(11) NOT NULL,
        dom_caps_best int(11) NOT NULL,
        dom_caps_best_life int(11) NOT NULL,
        accuracy float NOT NULL,
        k_distance_normal int(11) NOT NULL,
        k_distance_long int(11) NOT NULL,
        k_distance_uber int(11) NOT NULL,
        headshots int(11) NOT NULL,
        shield_belt int(11) NOT NULL,
        amp int(11) NOT NULL,
        amp_time float NOT NULL,
        invisibility int(11) NOT NULL,
        invisibility_time float NOT NULL,
        pads int(11) NOT NULL,
        armor int(11) NOT NULL,
        boots int(11) NOT NULL,
        super_health int(11) NOT NULL,
        mh_kills int(11) NOT NULL,
        mh_kills_best_life int(11) NOT NULL,
        mh_kills_best int(11) NOT NULL,
        views int(11) NOT NULL,
        mh_deaths int(11) NOT NULL,
        mh_deaths_worst int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_player_weapon_match (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        map_id int(11) NOT NULL,
        gametype_id int(11) NOT NULL,
        player_id int(11) NOT NULL,
        weapon_id int(11) NOT NULL,
        kills int(11) NOT NULL,
        best_kills int(11) NOT NULL,
        deaths int(11) NOT NULL,
        suicides int(11) NOT NULL,
        team_kills int(11) NOT NULL,
        best_team_kills int(11) NOT NULL,
        accuracy float NOT NULL,
        shots int(11) NOT NULL,
        hits int(11) NOT NULL,
        damage bigint(11) NOT NULL,
        efficiency float NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_player_weapon_totals (
        id int(11) NOT NULL AUTO_INCREMENT,
        player_id int(11) NOT NULL,
        map_id int(11) NOT NULL,
        gametype int(11) NOT NULL,
        weapon int(11) NOT NULL,
        kills int(11) NOT NULL,
        team_kills int(11) NOT NULL,
        deaths int(11) NOT NULL,
        suicides int(11) NOT NULL,
        efficiency int(11) NOT NULL,
        accuracy float NOT NULL,
        shots int(11) NOT NULL,
        hits int(11) NOT NULL,
        damage bigint(11) NOT NULL,
        matches int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_ranking_player_current (
        id int(11) NOT NULL AUTO_INCREMENT,
        player_id int(11) NOT NULL,
        gametype int(11) NOT NULL,
        matches int(11) NOT NULL,
        playtime float NOT NULL,
        ranking Decimal(10,4) NOT NULL,
        ranking_change Decimal(10,4) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_ranking_player_history (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        player_id int(11) NOT NULL,
        gametype int(11) NOT NULL,
        ranking Decimal(10,4) NOT NULL,
        match_ranking Decimal(10,4) NOT NULL,
        ranking_change Decimal(10,4) NOT NULL,
        match_ranking_change Decimal(10,4) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_ranking_values (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(30) NOT NULL,
        display_name varchar(75) NOT NULL,
        description varchar(250) NOT NULL,
        value float NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_servers (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        ip varchar(100) NOT NULL,
        port int(5) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        matches int(11) NOT NULL,
        playtime double NOT NULL,
        display_name varchar(100) NOT NULL,
        display_address varchar(100) NOT NULL,
        password varchar(100) NOT NULL,
        country varchar(2) NOT NULL,
        last_match_id INT(11) NOT NULL,
        last_map_id INT(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_sessions (
        id int(11) NOT NULL AUTO_INCREMENT,
        date int(11) NOT NULL,
        user int(11) NOT NULL,
        hash varchar(64) NOT NULL,
        created int(11) NOT NULL,
        expires int(11) NOT NULL,
        login_ip varchar(50) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_site_settings (
        id int(11) NOT NULL AUTO_INCREMENT,
        category varchar(50) NOT NULL,
        name varchar(100) NOT NULL,
        value varchar(100) NOT NULL,
        page_order INT(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_sprees (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        player int(11) NOT NULL,
        kills int(11) NOT NULL,
        start_timestamp float NOT NULL,
        end_timestamp float NOT NULL,
        total_time float NOT NULL,
        killer int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_users (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(20) NOT NULL,
        password varchar(64) NOT NULL,
        joined int(11) NOT NULL,
        activated int(1) NOT NULL,
        logins int(11) NOT NULL,
        admin int(11) NOT NULL,
        last_login int(11) NOT NULL,
        last_active int(11) NOT NULL,
        last_ip varchar(50) NOT NULL,
        banned int(11) NOT NULL,
        upload_images int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_voices (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        uses int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_weapons (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        matches int(11) NOT NULL,
        kills int(11) NOT NULL,
        deaths int(11) NOT NULL,
        accuracy float NOT NULL,
        shots int(11) NOT NULL,
        hits int(11) NOT NULL,
        damage bigint(20) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_winrates (
        id int(11) NOT NULL AUTO_INCREMENT,
        date int(11) NOT NULL,
        match_id int(11) NOT NULL,
        player int(11) NOT NULL,
        gametype int(11) NOT NULL,
        match_result int(11) NOT NULL,
        matches int(11) NOT NULL,
        wins int(11) NOT NULL,
        draws int(11) NOT NULL,
        losses int(11) NOT NULL,
        winrate float NOT NULL,
        current_win_streak int(11) NOT NULL,
        current_draw_streak int(11) NOT NULL,
        current_lose_streak int(11) NOT NULL,
        max_win_streak int(11) NOT NULL,
        max_draw_streak int(11) NOT NULL,
        max_lose_streak int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
    `CREATE TABLE IF NOT EXISTS nstats_winrates_latest (
        id int(11) NOT NULL AUTO_INCREMENT,
        date int(11) NOT NULL,
        match_id int(11) NOT NULL,
        player int(11) NOT NULL,
        gametype int(11) NOT NULL,
        matches int(11) NOT NULL,
        wins int(11) NOT NULL,
        draws int(11) NOT NULL,
        losses int(11) NOT NULL,
        winrate float NOT NULL,
        current_win_streak int(11) NOT NULL,
        current_draw_streak int(11) NOT NULL,
        current_lose_streak int(11) NOT NULL,
        max_win_streak int(11) NOT NULL,
        max_draw_streak int(11) NOT NULL,
        max_lose_streak int(11) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

      `CREATE TABLE IF NOT EXISTS nstats_hits (
        id int(11) NOT NULL AUTO_INCREMENT,
        ip varchar(50) NOT NULL,
        date int(11) NOT NULL,
        PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

      `CREATE TABLE IF NOT EXISTS nstats_visitors (
          id int(11) NOT NULL AUTO_INCREMENT,
          ip varchar(50) NOT NULL,
          first int(11) NOT NULL,
          last int(11) NOT NULL,
          total int(11) NOT NULL,
          PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

      `CREATE TABLE IF NOT EXISTS nstats_visitors_countries (
        id int(11) NOT NULL AUTO_INCREMENT,
        code varchar(2) NOT NULL,
        country varchar(100) NOT NULL,
        first int(11) NOT NULL,
        last int(11) NOT NULL,
        total int(11) NOT NULL,
        PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

        `CREATE TABLE IF NOT EXISTS nstats_user_agents (
          id int(11) NOT NULL AUTO_INCREMENT,
          system_name varchar(100) NOT NULL,
          browser varchar(100) NOT NULL,
          first int(11) NOT NULL,
          last int(11) NOT NULL,
          total int(11) NOT NULL,
          PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,


    `CREATE TABLE IF NOT EXISTS nstats_ace_joins (
        id int(11) NOT NULL AUTO_INCREMENT,
        log_file varchar(255) NOT NULL,
        ace_version varchar(50) NOT NULL,
        timestamp int(11) NOT NULL,
        player varchar(30) NOT NULL,
        ip varchar(50) NOT NULL,
        country varchar(2) NOT NULL,
        os varchar(250) NOT NULL,
        mac1 varchar(32) NOT NULL,
        mac2 varchar(32) NOT NULL,
        hwid varchar(32) NOT NULL
      ,PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

      `CREATE TABLE IF NOT EXISTS nstats_ace_kicks (
        id int(11) NOT NULL AUTO_INCREMENT,
        file varchar(255) NOT NULL,
        raw_data LONGTEXT NOT NULL,
        name varchar(30) NOT NULL,
        ace_version varchar(20) NOT NULL,
        ip varchar(50) NOT NULL,
        country varchar(2) NOT NULL,
        os varchar(100) NOT NULL,
        cpu varchar(100) NOT NULL,
        cpu_speed decimal(10,5) NOT NULL,
        nic_desc varchar(100) NOT NULL,
        mac1 varchar(32) NOT NULL,
        mac2 varchar(32) NOT NULL,
        hwid varchar(32) NOT NULL,
        game_version int(4) NOT NULL,
        renderer varchar(100) NOT NULL,
        sound_device varchar(100) NOT NULL,
        command_line varchar(255) NOT NULL,
        timestamp int(11) NOT NULL,
        kick_reason varchar(100) NOT NULL,
        package_name varchar(100) NOT NULL,
        package_path varchar(100) NOT NULL,
        package_size int(11) NOT NULL,
        package_hash varchar(32) NOT NULL,
        package_version varchar(100) NOT NULL,
        screenshot_file varchar(255) NOT NULL,
        screenshot_status varchar(100) NOT NULL,
        PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

        `CREATE TABLE IF NOT EXISTS nstats_ace_players (
          id int(11) NOT NULL AUTO_INCREMENT,
          name varchar(30) NOT NULL,
          ip varchar(50) NOT NULL,
          country varchar(2) NOT NULL,
          mac1 varchar(32) NOT NULL,
          mac2 varchar(32) NOT NULL,
          hwid varchar(32) NOT NULL,
          first int(11) NOT NULL,
          last int(11) NOT NULL,
          times_connected int(11) NOT NULL,
          times_kicked int(11) NOT NULL,
          last_kick int(11) NOT NULL,
          PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

        `CREATE TABLE IF NOT EXISTS nstats_ace_sshot_requests (
          id int(11) NOT NULL AUTO_INCREMENT,
          file varchar(255) NOT NULL,
          raw_data LONGTEXT NOT NULL,
          player varchar(30) NOT NULL,
          ip varchar(50) NOT NULL,
          country varchar(2) NOT NULL,
          ace_version varchar(10) NOT NULL,
          os varchar(255) NOT NULL,
          cpu varchar(255) NOT NULL,
          cpu_speed decimal(10,5) NOT NULL,
          nic_desc varchar(255) NOT NULL,
          mac1 varchar(32) NOT NULL,
          mac2 varchar(32) NOT NULL,
          hwid varchar(32) NOT NULL,
          game_version int(4) NOT NULL,
          renderer varchar(255) NOT NULL,
          sound_device varchar(255) NOT NULL,
          command_line varchar(255) NOT NULL,
          timestamp int(11) NOT NULL,
          admin_name varchar(30) NOT NULL,
          screenshot_file varchar(255) NOT NULL,
          screenshot_status varchar(50) NOT NULL,
          PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

          `CREATE TABLE IF NOT EXISTS nstats_ace_screenshots (
            id int(11) NOT NULL AUTO_INCREMENT,
            name varchar(255) NOT NULL,
            date_downloaded int(11) NOT NULL,
            PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,


            `CREATE TABLE IF NOT EXISTS nstats_match_combogib (
              id int(11) NOT NULL AUTO_INCREMENT,
              player_id int(11) NOT NULL,
              gametype_id int(11) NOT NULL,
              match_id int(11) NOT NULL,
              map_id int(11) NOT NULL,
              playtime float NOT NULL,
              primary_kills int(11) NOT NULL,
              primary_deaths int(11) NOT NULL,
              primary_efficiency float NOT NULL,
              primary_kpm float NOT NULL,
              shockball_kills int(11) NOT NULL,
              shockball_deaths int(11) NOT NULL,
              shockball_efficiency float NOT NULL,
              shockball_kpm float NOT NULL,
              combo_kills int(11) NOT NULL,
              combo_deaths int(11) NOT NULL,
              combo_efficiency float NOT NULL,
              combo_kpm float NOT NULL,
              insane_kills INT(11) NOT NULL,
              insane_deaths INT(11) NOT NULL,
              insane_efficiency float NOT NULL,
              insane_kpm float NOT NULL,
              best_single_combo int(11) NOT NULL,
              best_single_shockball int(11) NOT NULL,
              best_single_insane int(11) NOT NULL,
              best_primary_spree int(11) NOT NULL,
              best_shockball_spree int(11) NOT NULL,
              best_combo_spree int(11) NOT NULL,
              best_insane_spree int(11) NOT NULL,
              PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
              `CREATE TABLE IF NOT EXISTS nstats_map_combogib (
                  id int(11) NOT NULL AUTO_INCREMENT,
                  map_id int(11) NOT NULL,
                  gametype_id int(11) NOT NULL,
                  matches int(11) NOT NULL,
                  playtime float NOT NULL,
                  primary_kills int(11) NOT NULL,
                  primary_kpm float NOT NULL,
                  shockball_kills int(11) NOT NULL,
                  shockball_kpm float NOT NULL,
                  combo_kills int(11) NOT NULL,
                  combo_kpm float NOT NULL,
                  insane_kills INT(11) NOT NULL,
                  insane_kpm float NOT NULL,
                  best_single_combo int(11) NOT NULL,
                  best_single_combo_player_id int(11) NOT NULL,
                  best_single_combo_match_id int(11) NOT NULL,
                  best_single_shockball int(11) NOT NULL,
                  best_single_shockball_player_id int(11) NOT NULL,
                  best_single_shockball_match_id int(11) NOT NULL,
                  best_single_insane int(11) NOT NULL,
                  best_single_insane_player_id int(11) NOT NULL,
                  best_single_insane_match_id int(11) NOT NULL,
                  best_primary_spree int(11) NOT NULL,
                  best_primary_spree_player_id int(11) NOT NULL,
                  best_primary_spree_match_id int(11) NOT NULL,
                  best_shockball_spree int(11) NOT NULL,
                  best_shockball_spree_player_id int(11) NOT NULL,
                  best_shockball_spree_match_id int(11) NOT NULL,
                  best_combo_spree int(11) NOT NULL,
                  best_combo_spree_player_id int(11) NOT NULL,
                  best_combo_spree_match_id int(11) NOT NULL,
                  best_insane_spree int(11) NOT NULL,
                  best_insane_spree_player_id int(11) NOT NULL,
                  best_insane_spree_match_id int(11) NOT NULL,
                  max_combo_kills int(11) NOT NULL,
                  max_combo_kills_player_id int(11) NOT NULL,
                  max_combo_kills_match_id int(11) NOT NULL,
                  max_insane_kills int(11) NOT NULL,
                  max_insane_kills_player_id int(11) NOT NULL,
                  max_insane_kills_match_id int(11) NOT NULL,
                  max_shockball_kills int(11) NOT NULL,
                  max_shockball_kills_player_id int(11) NOT NULL,
                  max_shockball_kills_match_id int(11) NOT NULL,
                  max_primary_kills int(11) NOT NULL,
                  max_primary_kills_player_id int(11) NOT NULL,
                  max_primary_kills_match_id int(11) NOT NULL,
  
                  PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  
                  `CREATE TABLE IF NOT EXISTS nstats_player_combogib (
                      id int(11) NOT NULL AUTO_INCREMENT,
                      player_id int(11) NOT NULL,
                      gametype_id int(11) NOT NULL,
                      map_id int(11) NOT NULL,
                      total_matches int(11) NOT NULL,
                      playtime float NOT NULL,
                      combo_kills int(11) NOT NULL,
                      combo_deaths int(11) NOT NULL,
                      combo_efficiency FLOAT NOT NULL,
                      combo_kpm float NOT NULL,
                      insane_kills INT(11) NOT NULL,
                      insane_deaths INT(11) NOT NULL,
                      insane_efficiency FLOAT NOT NULL,
                      insane_kpm float NOT NULL,
                      shockball_kills int(11) NOT NULL,
                      shockball_deaths int(11) NOT NULL,
                      shockball_efficiency FLOAT NOT NULL,
                      shockball_kpm float NOT NULL,
                      primary_kills int(11) NOT NULL,
                      primary_deaths int(11) NOT NULL,
                      primary_efficiency FLOAT NOT NULL,
                      primary_kpm float NOT NULL,      
  
                      best_single_combo int(11) NOT NULL,
                      best_single_combo_match_id int(11) NOT NULL,
                      best_single_insane int(11) NOT NULL,
                      best_single_insane_match_id int(11) NOT NULL,
                      best_single_shockball int(11) NOT NULL,
                      best_single_shockball_match_id int(11) NOT NULL,
                      
                      max_combo_kills int(11) NOT NULL,
                      max_combo_kills_match_id int(11) NOT NULL,
                      max_insane_kills int(11) NOT NULL,
                      max_insane_kills_match_id int(11) NOT NULL,
                      max_shockball_kills int(11) NOT NULL,
                      max_shockball_kills_match_id int(11) NOT NULL,
                      max_primary_kills int(11) NOT NULL,
                      max_primary_kills_match_id int(11) NOT NULL,
  
                      best_combo_spree int(11) NOT NULL,
                      best_combo_spree_match_id int(11) NOT NULL,
  
                      best_insane_spree int(11) NOT NULL,
                      best_insane_spree_match_id int(11) NOT NULL,
  
                      best_shockball_spree int(11) NOT NULL,
                      best_shockball_spree_match_id int(11) NOT NULL,
  
                      best_primary_spree int(11) NOT NULL,
                      best_primary_spree_match_id int(11) NOT NULL,
      
                      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,


    "INSERT INTO nstats_ranking_values VALUES(NULL,'frags','Kill','Player Killed an enemy',300)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'deaths','Death','Player died',-150)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'suicides','Suicide','Player killed themself',-150)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'team_kills','Team Kill','Player killed a team mate',-1200)",

    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_taken','Flag Grab','Player grabbed the flag from the enemy flag stand',600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_pickup','Flag Pickup','Player picked up a dropped enemy flag',600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_return','Flag Return','Player returned the players flag to their base',600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_capture','Flag Capture','Player capped the enemy flag',6000)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_seal','Flag Seal','Player sealed off the base while a team mate was carrying the flag',1200)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_assist','Flag Assist','Player had carry time of the enemy flag that was capped',3000)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_kill','Flag Kill','Player killed the enemy flag carrier.',1200)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_dropped','Flag Dropped','Player dropped the enemy flag',-300)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_cover','Flag Cover','Player killed an enemy close to a team mate carrying the flag',1800)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_cover_pass','Flag Successful Cover','Player covered the flag carrier that was later capped',1000)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_cover_fail','Flag Failed Cover','Player covered the flag carrier but the flag was returned',-600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_self_cover','Flag Self Cover','Player killed an enemy while carrying the flag',600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_self_cover_pass','Successful Flag Self Cover','Player killed an enemy while carrying the flag that was later capped',1000)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_self_cover_fail','Failed Flag Self Cover','Player killed an enemy while carrying the flag, but the flag was returned',-600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_multi_cover','Flag Multi Cover','Player covered the flag carrier 3 times while the enemy flag was taken one time',3600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_spree_cover','Flag Cover Spree','Player covered the flag carrier 4 or more times while the enemy flag was taken one time',4200)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'flag_save','Flag Close Save','Player returned their flag that was close to being capped by the enemy team',4000)",


    "INSERT INTO nstats_ranking_values VALUES(NULL,'dom_caps','Domination Control Point Caps','Player captured a contol point.',6000)",

    "INSERT INTO nstats_ranking_values VALUES(NULL,'assault_objectives','Assault Objectives','Player captured an assault objective.',6000)",

    "INSERT INTO nstats_ranking_values VALUES(NULL,'multi_1','Double Kill','Player killed 2 people in a short amount of time without dying',100)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'multi_2','Multi Kill','Player killed 3 people in a short amount of time without dying',150)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'multi_3','Mega Kill','Player killed 4 people in a short amount of time without dying',200)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'multi_4','Ultra Kill','Player killed 5 people in a short amount of time without dying',300)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'multi_5','Monster Kill','Player killed 6 people in a short amount of time without dying',450)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'multi_6','Ludicrous Kill','Player killed 7 people in a short amount of time without dying',600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'multi_7','Holy Shit','Player killed 8 or more people in a short amount of time without dying',750)",

    "INSERT INTO nstats_ranking_values VALUES(NULL,'spree_1','Killing Spree','Player killed 5 to 9 players in one life',600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'spree_2','Rampage','Player killed 10 to 14 players in one life',750)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'spree_3','Dominating','Player killed 15 to 19 players in one life',900)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'spree_4','Unstoppable','Player killed 20 to 24 players in one life',1200)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'spree_5','Godlike','Player killed 25 to 29 players in one life',1800)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'spree_6','Too Easy','Player killed 30 to 34 players in one life',2400)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'spree_7','Brutalizing the competition','Player killed 35 or more players in one life',3600)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'mh_kills','Monster Kills(MonsterHunt)','Player killed a monster',360)",


    `INSERT INTO nstats_ranking_values
     VALUES(
         NULL,
         'sub_half_hour_multiplier',
         'Sub 30 Minutes Playtime Penalty',
         'Reduce the player\\'s score to a percentage of it\\'s original value',
          0.05)`,


    `INSERT INTO nstats_logs_folder VALUES(NULL, 'Logs Folder',0,0,0,0,0,0,0,0,0,0,0,0,0)`,
    
    
    "INSERT INTO nstats_ranking_values VALUES(NULL,'sub_hour_multiplier','Sub 1 Hour Playtime Penalty Multiplier','Reduce the player\\'s score to a percentage of it\\'s original value', 0.2)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'sub_2hour_multiplier','Sub 2 Hour Playtime Penalty Multiplier','Reduce the player\\'s score to a percentage of it\\'s original value', 0.5)",
    "INSERT INTO nstats_ranking_values VALUES(NULL,'sub_3hour_multiplier','Sub 3 Hour Playtime Penalty Multiplier','Reduce the player\\'s score to a percentage of it\\'s original value', 0.75)",
    `INSERT INTO nstats_items VALUES(NULL,"AntiGrav Boots","Jump Boots",0,0,0,0,4)`,
    `INSERT INTO nstats_items VALUES(NULL,"Body Armor","Body Armor",0,0,0,0,3)`,
    `INSERT INTO nstats_items VALUES(NULL,"Chainsaw","Chainsaw",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Damage Amplifier","Damage Amplifier",0,0,0,0,4)`,
    `INSERT INTO nstats_items VALUES(NULL,"Double Enforcers","Double Enforcers",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Enforcer","Enforcer",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Enhanced Shock Rifle","Enhanced Shock Rifle",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Flak Cannon","Flak Cannon",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"GES Bio Rifle","GES Bio Rifle",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Health Pack","Health Pack",0,0,0,0,3)`,
    `INSERT INTO nstats_items VALUES(NULL,"Health Vial","Health Vial",0,0,0,0,3)`,
    `INSERT INTO nstats_items VALUES(NULL,"Invisibility","Invisibility",0,0,0,0,4)`,
    `INSERT INTO nstats_items VALUES(NULL,"Minigun","Minigun",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Pulse Gun","Pulse Gun",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Redeemer","Redeemer",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"RelicDeathInventory","Relic Death",0,0,0,0,5)`,
    `INSERT INTO nstats_items VALUES(NULL,"RelicDefenseInventory","Relic Defense",0,0,0,0,5)`,
    `INSERT INTO nstats_items VALUES(NULL,"RelicRedemptionInventory","Relic Redemption",0,0,0,0,5)`,
    `INSERT INTO nstats_items VALUES(NULL,"RelicRegenInventory","Relic Regen",0,0,0,0,5)`,
    `INSERT INTO nstats_items VALUES(NULL,"RelicSpeedInventory","Relic Speed",0,0,0,0,5)`,
    `INSERT INTO nstats_items VALUES(NULL,"RelicStrengthInventory","Relic Strength",0,0,0,0,5)`,
    `INSERT INTO nstats_items VALUES(NULL,"Ripper","Ripper",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Rocket Launcher","Rocket Launcher",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Shield Belt","Shield Belt",0,0,0,0,4)`,
    `INSERT INTO nstats_items VALUES(NULL,"ShieldBelt","Shield Belt",0,0,0,0,4)`,
    `INSERT INTO nstats_items VALUES(NULL,"Shock Rifle","Shock Rifle",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Sniper Rifle","Sniper Rifle",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Super Health Pack","Super Health Pack",0,0,0,0,4)`,
    `INSERT INTO nstats_items VALUES(NULL,"Thigh Pads","Thigh Pads",0,0,0,0,3)`,
    `INSERT INTO nstats_items VALUES(NULL,"Ammor Percing Slugs Pads","Armor Percing Slugs",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"AP CAS12","AP CAS12s",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Armor Shard","Armor Shard",0,0,0,0,3)`,
    `INSERT INTO nstats_items VALUES(NULL,"Arrows","Arrows",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"Blade Hopper","Ripper Ammo",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"Box of Rifle Rounds","Sniper Ammo",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"Box of RPB Rounds","RPB Sniper Ammo",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"CAS12","CAS12",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Chaos Sniper Rifle","Chaos Sniper Rifle",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Claw","Claw",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Crossbow","Crossbow",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Explosive Arrows","Crossbow",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"Explosive CAS12","Explosive CAS12",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Explosive Crossbow","Explosive Crossbow",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Explosive SG Shells","Explosive SG Shells",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"Flak Shells","Flak Shells",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"Gravity Belt","Gravity Belt",0,0,0,0,5)`,
    `INSERT INTO nstats_items VALUES(NULL,"Poison Crossbow","Poison Crossbow",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Proxy Mines","Proxy Mines",0,0,0,0,1)`,
    `INSERT INTO nstats_items VALUES(NULL,"Rocket Pack","Rocket Pack",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"SG Shells","SG Shell",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"Shock Core","Shock Core",0,0,0,0,2)`,
    `INSERT INTO nstats_items VALUES(NULL,"Sword","Sword",0,0,0,0,1)`,


    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Recent Matches To Display","3","10")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Recent Matches Display Type","0","9")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Most Played Gametypes","true","8")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Most Used Faces","true","7")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Most Played Maps","true","6")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Most Popular Countries","true","5")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Recent Players","true","4")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Addicted Players","true","1")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Latest Match","true","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Recent Matches","true","2")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Home","Display Recent Matches & Player Stats","true","3")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Addicted Players","true","11")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Control Points (Domination)","true","8")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Games Played","true","4")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Longest Matches","true","12")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Map Objectives (Assault)","true","7")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Recent Matches","true","5")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Spawn Points","true","13")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Summary","true","3")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Max Addicted Players","5","2")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Max Longest Matches","5","1")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Recent Matches Per Page","25","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display CTF Caps","true","6")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Combogib Player Records","true","10")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Map Pages","Display Combogib General Stats","true","9")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Maps Page","Default Display Per Page","25","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Maps Page","Default Display Type","0","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Match Report Title","true",0)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Summary","true",1)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Screenshot","true",2)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Domination Summary","true",3)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Domination Graphs","true",4)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Assault Summary","true",5)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Capture The Flag Summary","true",6)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Capture The Flag Graphs","true",7)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Capture The Flag Times","true",8)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Capture The Flag Caps","true",9)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Capture The Flag Returns","true",10)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Capture The Flag Carry Times","true",11)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display MonsterHunt Kills","true",12)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Frag Summary","true",13)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Frags Graphs","true",14)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Combogib Stats","true",15)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Special Events","true",16)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Extended Sprees","true",17)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Rankings","true",18)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Ammo Control","true",19)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Health/Armour Control","true",20)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Weapons Control","true",21)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Powerup Control","true",22)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Items Summary","true",23)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Pickup Summary","true",24)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Kills Match Up","true",25)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Weapon Statistics","true",26)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Player Ping Graph","true",27)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Players Connected to Server Graph","true",28)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Player Score Graph","true",29)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Team Changes","true",30)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Time Limit","true",31)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Server Settings","true",32)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Target Score","true",33)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Match Pages","Display Mutators","true",34)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Matches Page","Default Display Per Page","25","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Matches Page","Default Display Type","0","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Matches Page","Default Gametype","0","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Matches Page","Minimum Players","0","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Matches Page","Minimum Playtime","0","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Admin","true","7")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Home","true","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Login/Logout","true","8")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Maps","true","5")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Matches","true","1")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Players","true","2")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Rankings","true","3")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Records","true","4")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display ACE","true","6")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Default Recent Matches Display","0","21")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Default Weapon Display","0","20")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Recent Matches Per Page","25","18")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Aliases","true","15")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Pickup History","true","12")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Ping History Graph","true","16")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Recent Activity Graph","true","17")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Recent Matches","true","19")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Items Summary","true","14")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Weapon Stats","true","13")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Rankings","true","10")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Special Events","true","9")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Assault & Domination","true","6")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Capture The Flag Summary","true","5")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Frag Summary","true","2")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Gametype Stats","true","1")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Summary","true","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Capture The Flag Cap Records","true","7")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Monsterhunt Basic Stats","true","3")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Monsterhunt Monster Stats","true","4")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Player Pages","Display Combogib Stats","true","8")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Players Page","Default Display Per Page","25","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Players Page","Default Display Type","0","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Players Page","Default Order","ASC","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Players Page","Default Sort Type","name","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Rankings","Rankings Per Gametype (Main)","10","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Rankings","Rankings Per Page (Individual)","100","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Records Page","Display Player Records","true","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Records Page","Display Match Records","true","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Records Page","Display CTF Cap Records","true","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Records Page","Display Combogib Records","true","0")`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Records Page","Default Per Page","25",0)`,
    `INSERT INTO nstats_site_settings VALUES(NULL,"Navigation","Display Servers","true",0)`,

    

    `CREATE TABLE IF NOT EXISTS nstats_player_ctf_match (
      id int NOT NULL AUTO_INCREMENT,
      player_id int NOT NULL,
      match_id int NOT NULL,
      gametype_id int NOT NULL,
      server_id int NOT NULL,
      map_id int NOT NULL,
      match_date int NOT NULL,
      playtime float NOT NULL,
      flag_assist INT(11) NOT NULL,
      flag_assist_best INT(11) NOT NULL,
      flag_return INT(11) NOT NULL, 
      flag_return_best INT(11) NOT NULL, 
      flag_return_base INT(11) NOT NULL, 
      flag_return_base_best INT(11) NOT NULL, 
      flag_return_mid INT(11) NOT NULL, 
      flag_return_mid_best INT(11) NOT NULL, 
      flag_return_enemy_base INT(11) NOT NULL, 
      flag_return_enemy_base_best INT(11) NOT NULL, 
      flag_return_save INT(11) NOT NULL, 
      flag_return_save_best INT(11) NOT NULL, 
      flag_dropped INT(11) NOT NULL, 
      flag_dropped_best INT(11) NOT NULL, 
      flag_kill INT(11) NOT NULL, 
      flag_kill_best INT(11) NOT NULL, 
      flag_suicide INT(11) NOT NULL, 
      flag_seal INT(11) NOT NULL, 
      flag_seal_best INT(11) NOT NULL, 
      flag_seal_pass INT(11) NOT NULL, 
      flag_seal_pass_best INT(11) NOT NULL, 
      flag_seal_fail INT(11) NOT NULL, 
      flag_seal_fail_best INT(11) NOT NULL, 
      best_single_seal INT(11) NOT NULL, 
      flag_cover INT(11) NOT NULL, 
      flag_cover_best INT(11) NOT NULL, 
      flag_cover_pass INT(11) NOT NULL, 
      flag_cover_pass_best INT(11) NOT NULL, 
      flag_cover_fail INT(11) NOT NULL, 
      flag_cover_fail_best INT(11) NOT NULL, 
      flag_cover_multi INT(11) NOT NULL,
      flag_cover_multi_best INT(11) NOT NULL,
      flag_cover_spree INT(11) NOT NULL,
      flag_cover_spree_best INT(11) NOT NULL,
      best_single_cover INT(11) NOT NULL,
      flag_capture INT(11) NOT NULL, 
      flag_capture_best INT(11) NOT NULL, 
      flag_carry_time float NOT NULL, 
      flag_carry_time_best float NOT NULL, 
      flag_taken INT(11) NOT NULL,
      flag_taken_best INT(11) NOT NULL,
      flag_pickup INT(11) NOT NULL,
      flag_pickup_best INT(11) NOT NULL,
      flag_self_cover INT(11) NOT NULL,
      flag_self_cover_best INT(11) NOT NULL,
      flag_self_cover_pass INT(11) NOT NULL,
      flag_self_cover_pass_best INT(11) NOT NULL,
      flag_self_cover_fail INT(11) NOT NULL,
      flag_self_cover_fail_best INT(11) NOT NULL,
      best_single_self_cover INT(11) NOT NULL,
      flag_solo_capture INT(11) NOT NULL,
      flag_solo_capture_best INT(11) NOT NULL,
      PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,


      `CREATE TABLE IF NOT EXISTS nstats_powerups (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(100) NOT NULL,
        display_name varchar(100) NOT NULL,
        PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

      `CREATE TABLE nstats_powerups_carry_times (
        id int(11) NOT NULL AUTO_INCREMENT,
        match_id int(11) NOT NULL,
        match_date int(11) NOT NULL,
        player_id int(11) NOT NULL,
        powerup_id int(11) NOT NULL,
        start_timestamp float NOT NULL,
        end_timestamp float NOT NULL,
        carry_time float NOT NULL,
        kills int(11) NOT NULL,
        end_reason int(1) NOT NULL,
        PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

        `CREATE TABLE nstats_powerups_player_match (
          id int NOT NULL AUTO_INCREMENT,
          match_id int NOT NULL,
          match_date int NOT NULL,
          map_id int NOT NULL,
          gametype_id int NOT NULL,
          player_id int NOT NULL,
          powerup_id int NOT NULL,
          times_used int NOT NULL,
          carry_time float NOT NULL,
          carry_time_best float NOT NULL,
          total_kills int NOT NULL,
          best_kills int NOT NULL,
          end_deaths int NOT NULL,
          end_suicides int NOT NULL,
          end_timeouts int NOT NULL,
          end_match_end int NOT NULL,
          carrier_kills int NOT NULL,
          carrier_kills_best int NOT NULL,
          PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

          `CREATE TABLE nstats_powerups_player_totals (
            id int NOT NULL AUTO_INCREMENT,
            player_id int NOT NULL,
            gametype_id int NOT NULL,
            total_matches int NOT NULL,
            total_playtime float NOT NULL,
            powerup_id int NOT NULL,
            times_used int NOT NULL,
            times_used_best int NOT NULL,
            carry_time float NOT NULL,
            carry_time_best float NOT NULL,
            total_kills int NOT NULL,
            best_kills int NOT NULL,
            best_kills_single_use int NOT NULL,
            end_deaths int NOT NULL,
            end_suicides int NOT NULL,
            end_timeouts int NOT NULL,
            end_match_end int NOT NULL,
            total_carrier_kills int NOT NULL,
            carrier_kills_best int NOT NULL,
            carrier_kills_single_life int NOT NULL,
            PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,


            `CREATE TABLE IF NOT EXISTS nstats_player_ctf_totals (
              id int NOT NULL AUTO_INCREMENT,
              player_id int NOT NULL,
              gametype_id int NOT NULL,
              total_matches int NOT NULL,      
              playtime float NOT NULL,
              flag_assist INT(11) NOT NULL,
              flag_return INT(11) NOT NULL, 
              flag_return_base INT(11) NOT NULL, 
              flag_return_mid INT(11) NOT NULL, 
              flag_return_enemy_base INT(11) NOT NULL, 
              flag_return_save INT(11) NOT NULL, 
              flag_dropped INT(11) NOT NULL, 
              flag_kill INT(11) NOT NULL, 
              flag_suicide INT(11) NOT NULL, 
              flag_seal INT(11) NOT NULL, 
              flag_seal_pass INT(11) NOT NULL, 
              flag_seal_fail INT(11) NOT NULL, 
              best_single_seal INT(11) NOT NULL, 
              flag_cover INT(11) NOT NULL, 
              flag_cover_pass INT(11) NOT NULL, 
              flag_cover_fail INT(11) NOT NULL, 
              flag_cover_multi INT(11) NOT NULL,
              flag_cover_spree INT(11) NOT NULL,
              best_single_cover INT(11) NOT NULL,
              flag_capture INT(11) NOT NULL, 
              flag_carry_time float NOT NULL, 
              flag_taken INT(11) NOT NULL,
              flag_pickup INT(11) NOT NULL,
              flag_self_cover INT(11) NOT NULL,
              flag_self_cover_pass INT(11) NOT NULL,
              flag_self_cover_fail INT(11) NOT NULL,
              best_single_self_cover INT(11) NOT NULL,
              flag_solo_capture INT(11) NOT NULL,
              PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

              `CREATE TABLE IF NOT EXISTS nstats_player_ctf_best (
                id int NOT NULL AUTO_INCREMENT,
                player_id int NOT NULL,
                gametype_id int NOT NULL,
                flag_assist INT(11) NOT NULL,
                flag_return INT(11) NOT NULL, 
                flag_return_base INT(11) NOT NULL, 
                flag_return_mid INT(11) NOT NULL, 
                flag_return_enemy_base INT(11) NOT NULL, 
                flag_return_save INT(11) NOT NULL, 
                flag_dropped INT(11) NOT NULL, 
                flag_kill INT(11) NOT NULL, 
                flag_suicide INT(11) NOT NULL, 
                flag_seal INT(11) NOT NULL, 
                flag_seal_pass INT(11) NOT NULL, 
                flag_seal_fail INT(11) NOT NULL, 
                best_single_seal INT(11) NOT NULL, 
                flag_cover INT(11) NOT NULL, 
                flag_cover_pass INT(11) NOT NULL, 
                flag_cover_fail INT(11) NOT NULL, 
                flag_cover_multi INT(11) NOT NULL,
                flag_cover_spree INT(11) NOT NULL,
                best_single_cover INT(11) NOT NULL,
                flag_capture INT(11) NOT NULL, 
                flag_carry_time float NOT NULL, 
                flag_taken INT(11) NOT NULL,
                flag_pickup INT(11) NOT NULL,
                flag_self_cover INT(11) NOT NULL,
                flag_self_cover_pass INT(11) NOT NULL,
                flag_self_cover_fail INT(11) NOT NULL,
                best_single_self_cover INT(11) NOT NULL,
                flag_solo_capture INT(11) NOT NULL,
                PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

                `CREATE TABLE IF NOT EXISTS nstats_player_ctf_best_life (
                  id int NOT NULL AUTO_INCREMENT,
                  player_id int NOT NULL,
                  gametype_id int NOT NULL,
                  flag_assist INT(11) NOT NULL,
                  flag_return INT(11) NOT NULL, 
                  flag_return_base INT(11) NOT NULL, 
                  flag_return_mid INT(11) NOT NULL, 
                  flag_return_enemy_base INT(11) NOT NULL, 
                  flag_return_save INT(11) NOT NULL, 
                  flag_dropped INT(11) NOT NULL, 
                  flag_kill INT(11) NOT NULL, 
                  flag_seal INT(11) NOT NULL, 
                  flag_seal_pass INT(11) NOT NULL, 
                  flag_seal_fail INT(11) NOT NULL, 
                  best_single_seal INT(11) NOT NULL, 
                  flag_cover INT(11) NOT NULL, 
                  flag_cover_pass INT(11) NOT NULL, 
                  flag_cover_fail INT(11) NOT NULL, 
                  flag_cover_multi INT(11) NOT NULL,
                  flag_cover_spree INT(11) NOT NULL,
                  best_single_cover INT(11) NOT NULL,
                  flag_capture INT(11) NOT NULL, 
                  flag_carry_time float NOT NULL, 
                  flag_taken INT(11) NOT NULL,
                  flag_pickup INT(11) NOT NULL,
                  flag_self_cover INT(11) NOT NULL,
                  flag_self_cover_pass INT(11) NOT NULL,
                  flag_self_cover_fail INT(11) NOT NULL,
                  best_single_self_cover INT(11) NOT NULL,
                  flag_solo_capture INT(11) NOT NULL,
                  PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,


                  `CREATE TABLE IF NOT EXISTS nstats_ctf_cap_records(
                    id int(11) NOT NULL AUTO_INCREMENT,
                    cap_id INT(11) NOT NULL,
                    map_id INT(11) NOT NULL,
                    gametype_id INT(11) NOT NULL,
                    match_id INT(11) NOT NULL,
                    travel_time float NOT NULL,
                    carry_time float NOT NULL,
                    drop_time float NOT NULL,
                    cap_type INT(1) NOT NULL,
            PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,

];


(async () =>{


    const basicQuery = (query) =>{

        return new Promise((resolve, reject) =>{

            mysql.query(query, (err) =>{

                if(err) reject(err);

                resolve();
            });
        });
    }   

    try{
        
        for(let i = 0; i < queries.length; i++){

            
            await basicQuery(queries[i]);

            if(i === 0){
                mysql.end();
                mysql = mysqlObject.createPool({
                    "host": config.mysql.host,
                    "user": config.mysql.user,
                    "password": config.mysql.password,
                    "database": config.mysql.database
                });
            }
            new Message(`Performed query ${i+1} of ${queries.length}`,"pass");
        
        }

        mysql.end();

        const seed = Functions.generateRandomString(10000);


        const fileContents = `module.exports = () => {  return \`${seed}\`;}`;

        fs.writeFileSync("./salt.js", fileContents);

        process.exit();

    }catch(err){
        console.trace(err);
    }
})();

