import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./UI/Nav";
import { cookies } from "next/headers";
import UpdateSession from "./UpdateSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Node UTStats 2",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

	const cookieStore = cookies();

	const username = cookieStore.get("nstats_name")?.value ?? null;

	
	return (
		<html lang="en">
		<body className={inter.className}>
			<UpdateSession />
			<Nav username={username}/>
			<div className="padding-top"></div>
			{children}
			<footer>Horse Noise</footer>
		</body>
		</html>
	);
}
