import "../../styles/globals.css";
import Footer from "../../components/Footer";

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default async function RootLayout({ children }) {



return (
	<html lang="en">
		<body>
			<main>
				{children}
				<Footer/>
			</main>	
		</body>
	</html>
	)
}
